### ISSUE TITLE
Error connecting

### ISSUE THREAD

**Issue by ux287** [darikg/PgcliSublime#10]
I connect via ssh and am able to successfully query my database via said tunnel with pgcli in my terminal. In Sublime 3 however, using:

postgresql://[user]:[password]@localhost:[2345]/[dbname]

I get ERROR CONNECTING and the following log:

`pgcli_sublime: ERROR: Error connecting to pgcli
pgcli_sublime: ERROR: traceback: Traceback (most recent call last):
  File "pgcli_sublime in /Users/*username*/Library/Application Support/Sublime Text 3/Installed Packages/PgcliSublime.sublime-package", line 337, in check_pgcli
  File "pgcli_sublime in /Users/*username*/Library/Application Support/Sublime Text 3/Installed Packages/PgcliSublime.sublime-package", line 403, in new_executor
NameError: global name 'PGExecute' is not defined`

Any help would be greatly appreciated. Thanks.

**Comment by darikg** [comment]
Hi, I think maybe pgclisublime can't find pgcli from within sublime text. To confirm that can you run `import pgcli` at the sublime text console -- it should throw an `ImportError: No module named 'pgcli'` if that's the case. When you run pgcli from the terminal, where is it installed? In a virtual environment or the system python? What version of python is the terminal using?

**Comment by ux287** [comment]
That is correct, I get `ImportError: No module named 'pgcli'` 

Running `which pgcli` returns `/usr/local/bin/pgcli`. I installed it via homebrew.

Python version - 2.7.10

**Comment by darikg** [comment]
Ok, got it. 

So the giant pain in the ass is that Sublime Text is packaged with its own python build (python 3.3). So we need to 1) install a python 3.3 compatible version of pgcli and 2) get that on the sublime text 3 python path. 

What I recommend is 
1. creating a python 3.3 virtual environment
2. installing & getting pgcli working inside that
3. editing the PgcliSublime user settings to add your virtual environment's site-packages directory to the pgcli_site_dirs list

I know this is awful but I don't know how to fix it. :cry: I'm happy to help with any of these steps if you're unfamiliar with virtual environments

**Comment by ux287** [comment]
Thanks for all the info, and no worries. Just glad there's a solution out there that will get me away from using Postico for my SQL reporting (it's way more awful). Tried working through Google to figure out how to implement your instructions but not successful. I'm new to all of this. What are the next steps?

**Comment by darikg** [comment]
Ok here's how I would do it. I don't have a Mac but I think it should work.
1. Install [Miniconda](http://conda.pydata.org/docs/install/quick.html#os-x-miniconda-install) (It doesn't matter if you use the python 2 version or 3)
2. Create a new virtual environment: `conda create -n pgcli_sublime python=3.3 pip` (The -n flag means 'name', you can use whatever you want)
   - Make a note of where conda tells you the virtual environment is created. On windows it's `C:\Users\dg\Miniconda\envs\pgcli_sublime`
3. Activate the environment: `source activate pgcli_sublime`
4. Install psycopg2 into the virtual environment: `pip install psycopg2`. 
   - This is the hardest part. We need to use pip so that psycopg2 gets installed into the virtual environment against the python 3.3 version we specified. From some googling around I did I'm pretty this will work fine because you already have Postgresql itself installed. If this fails you may need to first add it to your path: `export PATH=$PATH:/path/to/postgreqsl/bin`
5. Install pgcli `pip install pgcli`
6. Make sure pgcli works as usual: `pgcli postgresql://blahblahblah`
7. In sublime text, edit the PgcliSublime text user settings as described [here](https://github.com/darikg/PgcliSublime#settings) to add your virtual environment's site-packages dir to the `pgcli_site_dirs` list. For me, the site-dirs path is `C:\Users\dg\Miniconda\envs\pgcli_sublime\Lib\site-packages`

**Comment by ux287** [comment]
Ok. Did all of that but still the same result. Here's what I have at the end:

`which python3 
~/miniconda3/bin/python3`

`echo $PATH
/Users/user/miniconda3/bin:/usr...`

`pgcli postgresql://blah
dbname >`

PGcliSublime user settings:

`"pgcli_site_dirs":        ["/Users/user/miniconda3/envs/pgcli_sublime/lib/python3.3/site-packages"],`
`"pgcli_url":  "postgresql://[username]:[password]@localhost:2345/lisa",`

Loading a sql file results in ERROR CONNECTING and the following log (same as before):

`pgcli_sublime: ERROR: Error connecting to pgcli
pgcli_sublime: ERROR: traceback: Traceback (most recent call last):
  File "pgcli_sublime in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/PgcliSublime.sublime-package", line 337, in check_pgcli
  File "pgcli_sublime in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/PgcliSublime.sublime-package", line 403, in new_executor
NameError: global name 'PGExecute' is not defined`

Thanks again for all the help. Thoughts on what to try next? Something I didn't complete correctly in your instructions?

**Comment by darikg** [comment]
That's frustrating. Inside the virtual environment, can you run `pip list` and copy the contents? Maybe pgcli was installed somewhere other than site-packages. Also, inside the sublime text console, if you scroll up, are there any error messages from pgclisublime from when sublime text is first opened?

**Comment by ux287** [comment]
`pip list`
click (6.6)
configobj (5.0.6)
pgcli (0.20.1)
pgspecial (1.3.0)
pip (8.0.3)
prompt-toolkit (0.46)
psycopg2 (2.6.1)
Pygments (2.1.3)
setproctitle (1.1.9)
setuptools (20.1.1)
six (1.10.0)
sqlparse (0.1.16)
wcwidth (0.1.6)
wheel (0.29.0)

I removed the pgcli_sublime package and reinstalled it. This was output to the log:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 120, in reload_plugin
    m.plugin_loaded()
  File "pgcli_sublime in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/PgcliSublime.sublime-package", line 50, in plugin_loaded
  File "/Users/user/miniconda3/envs/pgcli_sublime/lib/python3.3/site-packages/pgcli/main.py", line 39, in <module>
    from .pgexecute import PGExecute
  File "/Users/user/miniconda3/envs/pgcli_sublime/lib/python3.3/site-packages/pgcli/pgexecute.py", line 3, in <module>
    import psycopg2
  File "/Users/user/miniconda3/envs/pgcli_sublime/lib/python3.3/site-packages/psycopg2/**init**.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: dlopen(/Users/user/miniconda3/envs/pgcli_sublime/lib/python3.3/site-packages/psycopg2/_psycopg.so, 2): Library not loaded: libssl.1.0.0.dylib
  Referenced from: /Users/user/miniconda3/envs/pgcli_sublime/lib/python3.3/site-packages/psycopg2/_psycopg.so
  Reason: image not found
reloading plugin PgcliSublime.pgcli_sublime_repl
reloading Packages/PgcliSublime/PgcliSublime.sublime_settings
reloading Packages/User/Preferences.sublime-settings
pgcli_sublime: ERROR: Error connecting to pgcli
pgcli_sublime: ERROR: traceback: Traceback (most recent call last):
  File "pgcli_sublime in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/PgcliSublime.sublime-package", line 337, in check_pgcli
  File "pgcli_sublime in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/PgcliSublime.sublime-package", line 403, in new_executor
NameError: global name 'PGExecute' is not defined

**Comment by darikg** [comment]
Shoot, it looks like psycogp2 isn't working inside the virtual environment. If you run 

```
source activate pgcli_sublime
python -c "import psycopg2"
```

 you get this error, right?

`ImportError: dlopen(/Users/user/miniconda3/envs/pgcli_sublime/lib/python3.3/site-packages/psycopg2/_psycopg.so, 2): Library not loaded: libssl.1.0.0.dylib`

Could you try running 

```
source activate pgcli_sublime
conda install psycopg2
```

? Apparently conda installs better in macos better than pip. If that doesn't work we have might to tweak some more path variables

**Comment by ux287** [comment]
That did the trick! 

Anything to do to formalize what I have or should I be able to setup my ssh tunnel and then open .sql file in Sublime?

**Comment by darikg** [comment]
I think it should "just work" but I have no idea!

**Comment by ux287** [comment]
Cool man. Thanks so much for all the help. Much appreciated.
